
[tools]
rojo = "upliftgames/rojo@7.4.0-uplift.syncback.rc.9"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
wally-patch-package="Barocena/wally-patch-package@1.2.1"
lune = "filiptibell/lune@0.8.2"
