name = "corecii/greentea"
version = "0.4.9"
description = "A runtime typechecker with Luau types, pretty errors, and inspection"
authors = ["Corecii (Shae A.) <github.com/corecii>"]
repository = "https://github.com/Corecii/GreenTea"
license = "MIT"

includes = [
	"pesde.toml",
	"README.md",
	"CHANGELOG.md",
	"LICENSE",
	"src",
	"selene.toml",
	".luaurc",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
