
# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/filiptibell/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.
[tools]
rojo = "upliftgames/rojo@7.4.0-uplift.syncback.rc.17"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
wally-patch-package="Barocena/wally-patch-package@1.2.1"
lune = "filiptibell/lune@0.8.2"
lunar = "corecii/lunar@0.1.0"
